version: '3.8'

services:
  postgres-db-team:
    image: postgres:15-alpine
    container_name: prostor-db-team
    restart: always
    environment:
      POSTGRES_DB: prostor_db_team
      POSTGRES_USER: db_team
      POSTGRES_PASSWORD: team123
    ports:
      - "5434:5432"
    volumes:
      - postgres_db_team_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_team -d prostor_db_team"]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    container_name: prostor-adminer-team
    ports:
      - "8082:8080"
    depends_on:
      - postgres-db-team

volumes:
  postgres_db_team_data: